name: tasks_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  hive_flutter: ^1.1.0
  dio: ^5.7.0
  get_it: ^8.0.2
  flutter_dotenv: ^5.2.1
  equatable: ^2.0.5
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.3
  auto_route: ^7.8.4
  freezed_annotation: ^2.4.4
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  loading_animation_widget: ^1.3.0
  flutter_svg: ^2.0.14
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  auto_route_generator: ^7.3.2

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true
